In [1]:
import pandas as pd
from pathlib import Path

data_root = Path("/cs-share/pradalier/tmp/judo/data")
annotation_path = (
    data_root / "annotations" / "entity-detection-at-2024-04-05-12-52-6eba090e.json"
)

df = pd.read_json(annotation_path, orient="records")
df.head()

,id,annotations,file_upload,drafts,predictions,data,meta,created_at,updated_at,inner_id,total_annotations,cancelled_annotations,total_predictions,comment_count,unresolved_comment_count,last_comment_updated_at,project,updated_by,comment_authors
0,36121,"[{'id': 2424, 'completed_by': 1, 'result': [{'...",6d671d5f-frame_files.txt,[],[],{'image': 'http://localhost:8080/data/frames/m...,{},2024-02-13 15:30:06.306570+00:00,2024-02-15 17:06:11.247297+00:00,1,1,0,0,0,0,NaT,2,1,[]
1,36122,"[{'id': 2519, 'completed_by': 4, 'result': [{'...",6d671d5f-frame_files.txt,"[{'id': 42, 'user': 'acmiyaguchi@gatech.edu', ...",[192],{'image': 'http://localhost:8080/data/frames/m...,{},2024-02-13 15:30:06.306631+00:00,2024-02-20 12:58:18.826483+00:00,2,1,0,1,0,0,NaT,2,4,[]
2,36123,"[{'id': 2425, 'completed_by': 1, 'result': [{'...",6d671d5f-frame_files.txt,[],[94],{'image': 'http://localhost:8080/data/frames/m...,{},2024-02-13 15:30:06.306662+00:00,2024-02-15 17:12:19.211326+00:00,3,1,0,1,0,0,NaT,2,1,[]
3,36124,"[{'id': 2426, 'completed_by': 1, 'result': [{'...",6d671d5f-frame_files.txt,[],[95],{'image': 'http://localhost:8080/data/frames/m...,{},2024-02-13 15:30:06.306691+00:00,2024-02-15 17:12:22.123994+00:00,4,1,0,1,0,0,NaT,2,1,[]
4,36125,"[{'id': 2427, 'completed_by': 1, 'result': [{'...",6d671d5f-frame_files.txt,[],[96],{'image': 'http://localhost:8080/data/frames/m...,{},2024-02-13 15:30:06.306717+00:00,2024-02-15 17:12:38.755950+00:00,5,1,0,1,0,0,NaT,2,1,[]

In [17]:
df["image"] = (
    df["data"]
    .apply(lambda x: x["image"].replace("http://localhost:8080/data/frames/", ""))
    .astype(str)
)
df.image

0       mat_01/0003/0450.jpg
1       mat_01/0003/0425.jpg
2       mat_01/0003/0475.jpg
3       mat_01/0003/0024.jpg
4       mat_01/0003/0240.jpg
                ...
1646    mat_07/0002/0528.jpg
1647    mat_07/0002/0082.jpg
1648    mat_07/0002/0259.jpg
1649    mat_07/0002/0236.jpg
1650    mat_07/0002/0105.jpg
Name: image, Length: 1651, dtype: object